import sqlite3
from pathlib import Path

import pandas as pd


DB_PATH = Path("data/warehouse/network_ops.db")
ANOMALY_PATH = Path("ML/ML4/network_anomaly_scores.csv")
REPORT_PATH = Path("ML/ML6/top20_operational_attention_report.md")


def main():
    with sqlite3.connect(DB_PATH) as conn:
        scores = pd.read_sql_query(
            """
            SELECT
                grid_id,
                timestamp,
                risk_score,
                risk_level,
                model_version
            FROM network_risk_scores
            """,
            conn,
        )

    if scores.empty:
        raise RuntimeError("network_risk_scores is empty.")

    scores["grid_id"] = scores["grid_id"].astype(str)
    scores["timestamp"] = pd.to_datetime(scores["timestamp"])

    latest_timestamp = scores["timestamp"].max()

    latest = (
        scores[scores["timestamp"] == latest_timestamp]
        .sort_values("risk_score", ascending=False)
        .head(20)
        .copy()
    )

    anomaly = pd.read_csv(ANOMALY_PATH)

    anomaly["grid_id"] = anomaly["grid_id"].astype(str)
    anomaly["timestamp"] = pd.to_datetime(anomaly["timestamp"])

    anomaly = anomaly[
        anomaly["timestamp"] == latest_timestamp
    ][
        [
            "grid_id",
            "timestamp",
            "anomaly_score",
            "direction",
            "reason",
        ]
    ].copy()

    latest = latest.merge(
        anomaly,
        on=["grid_id", "timestamp"],
        how="left",
        validate="one_to_one",
    )

    if len(latest) != 20:
        raise RuntimeError(
            f"Expected 20 report rows, got {len(latest)}."
        )

    matched = latest["anomaly_score"].notna().sum()

    if matched != 20:
        raise RuntimeError(
            f"Expected 20 ML4 matches, got {matched}."
        )

    lines = [
        "# ML6 — Top-20 Operational Attention Report",
        "",
        "Scores are generated by ML3-v1.",
        "",
        "Risk is an operational attention signal and "
        "does not confirm a network fault or congestion.",
        "",
        f"Latest scored timestamp: {latest_timestamp}",
        "",
        "| Rank | Grid | Risk Score | Risk Level | "
        "Model Version | Anomaly Score | Direction | "
        "Operational Attention |",
        "|---:|---|---:|---|---|---:|---|---|",
    ]

    for rank, row in enumerate(
        latest.itertuples(index=False),
        start=1,
    ):
        anomaly_score = f"{row.anomaly_score:.2f}"

        if row.direction == "high":
            attention = (
                "High future high-activity risk with a current "
                "historical anomaly. Investigate the grid."
            )
        elif row.direction == "low":
            attention = (
                "High future high-activity risk; current activity "
                "is below its historical baseline. Investigate the grid."
            )
        else:
            attention = (
                "High future high-activity risk; current activity "
                "is within historical bounds. Investigate the grid "
                "based on the predictive signal."
            )

        lines.append(
            f"| {rank} | "
            f"{row.grid_id} | "
            f"{row.risk_score:.4f} | "
            f"{row.risk_level} | "
            f"{row.model_version} | "
            f"{anomaly_score} | "
            f"{row.direction} | "
            f"{attention} |"
        )

    REPORT_PATH.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print("ML6 — Report Regeneration")
    print("=" * 60)
    print(f"Latest timestamp : {latest_timestamp}")
    print(f"Top-20 rows      : {len(latest)}")
    print(f"ML4 matches      : {matched}/20")
    print(f"Report           : {REPORT_PATH}")
    print("Status           : PASS")


if __name__ == "__main__":
    main()
